const productsData = [
  {
    name: "Calabrese Broccoli",
    category: "Vegetable",
    price: 20,
    discount: 13,
    rating: 4,
    image: "broccoli.png",
  },
  {
    name: "Fresh Banana Fruites",
    category: "Fresh",
    price: 20,
    discount: 6,
    rating: 5,
    image: "banana.png",
  },
  {
    name: "White Nuts",
    category: "Millets",
    price: 20,
    discount: 3,
    rating: 3,
    image: "white-nuts.png",
  },
  {
    name: "Vegan Red Tomato",
    category: "Vegetable",
    price: 18,
    discount: 0,
    rating: 4,
    image: "vegan-red-tomato.png",
  },
  {
    name: "Mung Bean",
    category: "Health",
    price: 9,
    discount: 0,
    rating: 2,
    image: "mung-bean.png",
  },
  {
    name: "Brown Hazelnut",
    category: "Nuts",
    price: 14,
    discount: 5,
    rating: 4,
    image: "brown-hazelnut.png",
  },
  {
    name: "Eggs",
    category: "Fresh",
    price: 26,
    discount: 0,
    rating: 5,
    image: "eggs.png",
  },
  {
    name: "Zelco Suji Elaichi Rusk",
    category: "Fresh",
    price: 11,
    discount: 0,
    rating: 3,
    image: "elaichi-rusk.png",
  },
  {
    name: "Pickle",
    category: "Health",
    price: 16,
    discount: 5,
    rating: 4,
    image: "pickle.png",
  },
  {
    name: "White Hazelnut",
    category: "Fresh",
    price: 31,
    discount: 15,
    rating: 5,
    image: "white-hazelnut.png",
  },
  {
    name: "Fresh Corn",
    category: "Fresh",
    price: 18,
    discount: 0,
    rating: 4,
    image: "fresh-corn.png",
  },
  {
    name: "Organic Almonds",
    category: "Fresh",
    price: 15,
    discount: 2,
    rating: 3,
    image: "organic-almonds.png",
  },
  {
    name: "Romanesco Broccoli",
    category: "Vegetable",
    price: 23,
    discount: 0,
    rating: 5,
    image: "romanesco-broccoli.png",
  },
  {
    name: "Zucchini",
    category: "Vegetable",
    price: 3,
    discount: 0,
    rating: 2,
    image: "zucchini.png",
  },
  {
    name: "Onion",
    category: "Vegetable",
    price: 4,
    discount: 0,
    rating: 3,
    image: "onion.png",
  },
  {
    name: "Cabbage",
    category: "Vegetable",
    price: 8,
    discount: 2,
    rating: 5,
    image: "cabbage.png",
  },
];

module.exports = {
  productsData,
};
